import "./globals.css";
import { IBM_Plex_Mono } from "next/font/google";
import localFont from "next/font/local";
import cn from "classnames";
import { ChatConvoSelect, Layout } from "@/components";

const plexMono = IBM_Plex_Mono({
  subsets: ["latin-ext"],
  weight: ["400", "600"],
});

const mona = localFont({
  src: "./Mona-Sans.woff2",
  display: "swap",
  weight: "100 900",
  declarations: [
    {
      prop: "font-stretch",
      value: "75% 125%",
    },
  ],
});

export const metadata = {
  title: "Chat · LaURA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(mona.className, plexMono.className)}>
        <Layout leftPanelContent={<ChatConvoSelect />}>{children}</Layout>
      </body>
    </html>
  );
}
