name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install Node dependencies
        run: npm install --frozen-lockfile
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local # the path depends on the OS
          key: poetry-0 # increment to reset cache
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/.venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-
      - name: Install Python Dependencies
        run: |
          npx nx run-many --target=install --all --verbose
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish all Docker images
        run: npx nx affected --target=ci-build-publish --verbose
        env:
          GH_REPO: ${{ github.repository }}
