name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
      # TEMPORARY: Remove this once things are working
      - history-ci
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Inefficient build
        run: npx nx run-many --target=build --all --verbose
